[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
my_derive = { path = "../my_derive" }
avian2d = {version = "0.7.0", features = ["parallel", "simd"]}
bevy = {version = "0.19.1", features = ["debug"]}
chrono = "0.4.45"
uuid = "1.26.0"
rand = "0.10.2"
rand_distr = "0.6.0"
nalgebra = "0.35.0"
serde = "1.0.229"
serde_json = "1.0.151"
serde-big-array = "0.5.1"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]